# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Activities
    url: activities
    weight: 20
  - name:  340+337 - HCI Collaboratory
    url: hci
    parent: Activities
    weight: 21
  - name: 336 - Health Futures Lab
    url: health-futures
    parent: Activities
    weight: 22
  - name: 336 - Speculative Ecology & Bioarchitecture
    url: speculative
    parent: Activities
    weight: 23
  - name: 331 - Just Transitions
    url: transitions
    parent: Activities
    weight: 24
  - name: 331 - BioRegional Center
    url: bioregional
    parent: Activities
    weight: 25
  - name: 330 - Community Engagement Studio
    url: community
    parent: Activities
    weight: 26
  - name: Student Organizations
    url: student-orgs
    parent: Activities
    weight: 27
  - name: Featured and Others
    url: featured
    parent: Activities
    weight: 28
  - name: Map
    url: map
    weight: 30
  - name: People
    url: authors
    weight: 40
  - name: Contact
    url: contact
    weight: 50

